<a href="https://colab.research.google.com/github/SotaYoshida/Lecture_DataScience/blob/master/Python_misc_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandasの使い方 (基礎)

```Pandas```は、データ分析のためのライブラリで  
統計量を計算・表示したり、それらをグラフとして可視化出来たり  
データサイエンスや機械学習などで必要な作業を簡単に行うことができます。

Numpyや機械学習ライブラリなどに入れるデータの前処理などにもよく用いられます。

まずはインポートしましょう。```pd```という名前で使うのが慣例です。

In [95]:
import pandas as pd

## DataFrame型

DataFrameは二次元のデータを表現するのに利用され  
各種データ分析などで非常に役にたちます。

In [96]:
from pandas import DataFrame

以下の辞書型をDataFrame型のオブジェクトに変換してみましょう。

In [97]:
data = { '名前': ["Aさん", "Bさん", "Cさん", "Dさん", "Eさん"],
        '出身都道府県':['Tokyo', 'Tochigi', 'Hokkaido','Kyoto','Tochigi'],
        '生年': [ 1998, 1993,2000,1989,2002],
        '身長': [172, 156, 162, 180,158]}
df = DataFrame(data)
print("dataの型", type(data))
print("dfの型",type(df))

dataの型 <class 'dict'>
dfの型 <class 'pandas.core.frame.DataFrame'>

jupyter環境でDataFrameを読むと、"いい感じ"に表示してくれる

In [98]:
df

    名前    出身都道府県    生年   身長
0  Aさん     Tokyo  1998  172
1  Bさん   Tochigi  1993  156
2  Cさん  Hokkaido  2000  162
3  Dさん     Kyoto  1989  180
4  Eさん   Tochigi  2002  158

printだとちょっと無機質な感じに。

In [99]:
print(df)

    名前    出身都道府県    生年   身長
0  Aさん     Tokyo  1998  172
1  Bさん   Tochigi  1993  156
2  Cさん  Hokkaido  2000  162
3  Dさん     Kyoto  1989  180
4  Eさん   Tochigi  2002  158

```info()```関数を作用させると、詳細な情報が得られる。  
列ごとにどんな種類のデータが格納されているのかや、
メモリ使用量など表示することができる。

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   名前      5 non-null      object
 1   出身都道府県  5 non-null      object
 2   生年      5 non-null      int64
 3   身長      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 288.0+ bytes

## DataFrameの要素を確認・指定する方法

index: 行方向のデータ項目(おもに整数値(行番号),ID,名前など)  
columns: 列方向のデータの項目(おもにデータの種類)  
をそれぞれ表示してみよう。

In [101]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [102]:
df.columns

Index(['名前', '出身都道府県', '生年', '身長'], dtype='object')

行方向を、整数値(行数)ではなく名前にしたければ

In [103]:
data1 = {'出身都道府県':['Tokyo', 'Tochigi', 'Hokkaido','Kyoto','Tochigi'],
        '生年': [ 1998, 1993,2000,1989,2002],
        '身長': [172, 156, 162, 180,158]}
df1 = DataFrame(data1)
df1.index =["Aさん", "Bさん", "Cさん", "Dさん", "Eさん"]
df1

       出身都道府県    生年   身長
Aさん     Tokyo  1998  172
Bさん   Tochigi  1993  156
Cさん  Hokkaido  2000  162
Dさん     Kyoto  1989  180
Eさん   Tochigi  2002  158

などとしてもよい。

### 特定の列を取得したい場合

In [104]:
df["身長"]

0    172
1    156
2    162
3    180
4    158
Name: 身長, dtype: int64

とする。  
以下の方法は非推奨とする。

In [105]:
df.身長

0    172
1    156
2    162
3    180
4    158
Name: 身長, dtype: int64

値のリスト(正確にはnumpy.ndarray型)として取得したければ

In [106]:
df["身長"].values

array([172, 156, 162, 180, 158])

In [107]:
df["出身都道府県"].values

array(['Tokyo', 'Tochigi', 'Hokkaido', 'Kyoto', 'Tochigi'], dtype=object)

などとすればよい。

慣れ親しんだ形に変換したければ、リストに変換すればよい

In [108]:
list(df["出身都道府県"].values)

['Tokyo', 'Tochigi', 'Hokkaido', 'Kyoto', 'Tochigi']

ある列が特定のものに一致するもののみを抽出するのも簡単にできる

In [109]:
df[df["出身都道府県"]=="Tochigi"]

    名前   出身都道府県    生年   身長
1  Bさん  Tochigi  1993  156
4  Eさん  Tochigi  2002  158

これは

In [110]:
df["出身都道府県"]=="Tochigi"

0    False
1     True
2    False
3    False
4     True
Name: 出身都道府県, dtype: bool

が条件に合致するかどうかTrue/Falseの配列になっていて、  
df[ [True/Falseの配列] ]とすると、Trueに対応する要素のみを返す  
フィルターのような役割になっている。

### 特定の行を取得したい場合

たとえば、行番号がわかっているなら、```iloc```関数を使えば良い

In [111]:
df.iloc[3]

名前          Dさん
出身都道府県    Kyoto
生年         1989
身長          180
Name: 3, dtype: object

値のみ取得したければ先程と同様

In [112]:
df.iloc[3].values

array(['Dさん', 'Kyoto', 1989, 180], dtype=object)

また、以下のような使い方もできるが

In [113]:
df[1:4] #1から3行目まで

    名前    出身都道府県    生年   身長
1  Bさん   Tochigi  1993  156
2  Cさん  Hokkaido  2000  162
3  Dさん     Kyoto  1989  180

```df[1]```といった使い方は出来ない。

### より複雑な行・列の抽出

上にならって、2000年より前に生まれた人だけを抽出し

In [114]:
df[ df["生年"] < 2000 ]

    名前   出身都道府県    生年   身長
0  Aさん    Tokyo  1998  172
1  Bさん  Tochigi  1993  156
3  Dさん    Kyoto  1989  180

さらにこのうち身長が170cm以上の人だけがほしければ

In [115]:
df[(df["生年"] < 2000) & (df["身長"]>170)]

    名前 出身都道府県    生年   身長
0  Aさん  Tokyo  1998  172
3  Dさん  Kyoto  1989  180

などとすればよい。  

他にも、

```iloc```,```loc```
などを用いれば、特定の行・列を抽出することができる

ちなみに、```iloc```は番号の指定のみに対応，```loc```は名前のみ。

**欲しい要素の数値もしくは項目名のリスト**を、行、列２ついれてやればよい。

In [116]:
df.iloc[[0], [0]] #0行目,0列目

    名前
0  Aさん

In [117]:
#スライスで指定することもできる
df.iloc[1:4, :3] #1-3行目かつ0-2列目 (スライスの終点は含まれないことに注意)

#スライスの場合は、 1:4が[1,2,3]と同じ働きをするので、括弧[]はいらない

    名前    出身都道府県    生年
1  Bさん   Tochigi  1993
2  Cさん  Hokkaido  2000
3  Dさん     Kyoto  1989

```loc```を使う場合は、indexの代わりに項目名で指定する。

In [118]:
df.loc[1:4,["名前","身長"]]

    名前   身長
1  Bさん  156
2  Cさん  162
3  Dさん  180
4  Eさん  158

In [119]:
df.loc[[1,2,3,4],"名前":"生年"]

    名前    出身都道府県    生年
1  Bさん   Tochigi  1993
2  Cさん  Hokkaido  2000
3  Dさん     Kyoto  1989
4  Eさん   Tochigi  2002

といった具合。

```loc```を使う場合、1:4や[1,2,3,4]は  
indexのスライスではなく、項目名を意味し  
Eさんのデータも含まれている。

## Webページにある表をDataFrameとして取得する

```pandas```内の```read_html```関数を用いれば、  
Webページの中にある表をDataFrame形式で取得することもできます。

以下では例としてWikipediaの[ノーベル物理学賞](https://ja.wikipedia.org/wiki/%e3%83%8e%e3%83%bc%e3%83%99%e3%83%ab%e7%89%a9%e7%90%86%e5%ad%a6%e8%b3%9e)のページにある、受賞者一覧を取得してみましょう

In [120]:
url = "https://ja.wikipedia.org/wiki/%e3%83%8e%e3%83%bc%e3%83%99%e3%83%ab%e7%89%a9%e7%90%86%e5%ad%a6%e8%b3%9e"
tables = pd.read_html(url)

In [121]:
print(len(tables))

21

ページ内に、21個もの表があることがわかります。  
(ほとんどはwikipediaのテンプレート等)

たとえば、2010年代の受賞者のみに興味がある場合は

In [122]:
df = tables[12]
df

       年度  ...                                  受賞理由[2]・原著ないし関連論文
0   2010年  ...                          二次元物質グラフェンに関する革新的実験[注 69]
1   2010年  ...                          二次元物質グラフェンに関する革新的実験[注 69]
2   2011年  ...  遠方の超新星の観測を通した宇宙の加速膨張の発見Astrophys. J.: 517 (199...
3   2011年  ...  遠方の超新星の観測を通した宇宙の加速膨張の発見Astrophys. J.: 517 (199...
4   2011年  ...  遠方の超新星の観測を通した宇宙の加速膨張の発見Astrophys. J.: 517 (199...
5   2012年  ...  個別の量子系に対する計測および制御[注 70]を可能にする画期的な実験的手法に関する業績[3...
6   2012年  ...  個別の量子系に対する計測および制御[注 70]を可能にする画期的な実験的手法に関する業績[3...
7   2013年  ...  欧州原子核研究機構 (CERN) によって存在が確認された素粒子（ヒッグス粒子）に基づく、質...
8   2013年  ...  欧州原子核研究機構 (CERN) によって存在が確認された素粒子（ヒッグス粒子）に基づく、質...
9   2014年  ...                高輝度で省電力の白色光源を実現可能にした青色発光ダイオードの発明[8]
10  2014年  ...                高輝度で省電力の白色光源を実現可能にした青色発光ダイオードの発明[8]
11  2014年  ...                高輝度で省電力の白色光源を実現可能にした青色発光ダイオードの発明[8]
12  2015年  ...               素粒子「ニュートリノ」が質量を持つことを示すニュートリノ振動の発見[9]
13  2015年  ...               素粒子「ニュートリノ」が質量を持つことを示すニュートリノ振動の発見[9]
14  2016年  ...                 物質のトポロジカル相とトポロジカル相転移の理論的発見[10][11]
15  2016年  ...                 物質のトポロジカル相とトポロジカル相転移の理論的発見[10][11]
16  2016年  ...                 物質のトポロジカル相とトポロジカル相転移の理論的発見[10][11]
17  2017年  ...                           LIGO検出器および重力波の観測への決定的な貢献
18  2017年  ...                           LIGO検出器および重力波の観測への決定的な貢献
19  2017年  ...                           LIGO検出器および重力波の観測への決定的な貢献
20  2018年  ...                               光ピンセットの開発と生体システムへの応用
21  2018年  ...                             超高出力・超短パルスレーザーの生成方法の開発
22  2018年  ...                             超高出力・超短パルスレーザーの生成方法の開発
23  2019年  ...                                     物理宇宙論における理論的発見
24  2019年  ...                                太陽型恒星を周回する太陽系外惑星の発見
25  2019年  ...                                太陽型恒星を周回する太陽系外惑星の発見

[26 rows x 5 columns]

## DataFrameのcsv/Excelファイルへの書き出し

DataFrameオブジェクトは、```pandas```内の関数を用いれば、  
簡単にcsvやExcelファイルとして書き出すことができます。

先程の、２０１０年代のノーベル物理学賞受賞者のデータを、  
Google Driveに書き出してみましょう。

In [123]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**csvとして書き出す場合**

適当にパスを指定して、DataFrameオブジェクトに  
```to_csv```関数を作用させます。

In [124]:
df.to_csv("/content/drive/My Drive/AdDS2020/pd_write_test.csv")

**Excelファイルとして書き出す場合**

この場合も同様で、```to_excel```関数を用います。

In [125]:
df.to_excel("/content/drive/My Drive/AdDS2020/pd_write_test.xlsx")

上記の関数内で文字コードを指定することもできます。  
```
encoding="utf-8_sig"
```